### ISSUE TITLE
Add configuration for XLNet-Base

### ISSUE THREAD

**Issue by huzecong** [asyml/texar-pytorch#106]
The XLNet authors have just released a new pre-trained model checkpoint named `XLNet-Base, Cased` (https://github.com/zihangdai/xlnet#released-models). We should add support for this checkpoint.

**Comment by gpengzhi** [comment]
Thank you for the information. I think our current code structure should automatically support this checkpoint.

**Comment by huzecong** [comment]
@gpengzhi It's not just the checkpoint, but also the configs. We'll need to convert the config JSON file into Texar XLNet hparams, and currently we don't have such functionality.

**Comment by huzecong** [comment]
We could also take this chance to change everything to batch-first (now XLNet models use the 2nd dimension as the batch dimension). It would be nice to have a unified interface with the rest of the toolkit.

**Comment by gpengzhi** [comment]
Yes, we are building XLNet modules following a similar way of Bert/GPT2 modules. It will take care of both the checkpoint and the JSON file. @huzecong

**Comment by gpengzhi** [comment]
@AvinashBukkittu FYI, please change everything to batch-first as well in `texar-tensorflow`.
