### ISSUE TITLE
Multiple inheritance with `DecoderBase`

### ISSUE THREAD

**Issue by gpengzhi** [asyml/texar-pytorch#108]
An initialization issue will occur when we construct a class using multiple inheritances with `DecoderBase`. For example, we here have `class XLNetDecoder(XLNetEncoder, DecoderBase)`. When we call `super().__init__(...)` in `XLNetDecoder`, the initialization of `DecoderBase` can not be executed properly because of the parameter `input_size` in `DecoderBase.__init__()`. `hparams` is actually assigned to `input_size`, and `hparams` is set to be `None` in `ModuleBase`.

init order: `XLNetDecoder` -> `XLNetEncoder` -> `XLNetBase` -> `DecoderBase` -> `ModuleBase`.

**Comment by ZhitingHu** [comment]
Can we call the Parent class constructors explicitly? Like 
```
  __init__(..)
    XLNetEncoder.__int__(..)
    DecoderBase.__init__(..)
```

**Comment by gpengzhi** [comment]
In `XLNetDeocder`, we do not have the parameter `input_size`, while it is required in `DecoderBase`.

**Comment by gpengzhi** [comment]
I don't think this will work. `nn.Module.__init__()` will be called twice, and we will lose some parameters in the model. We probably can just delete the parameters `intput_size` or make it `Optional` since it is not used in `DecoderBase`.
