### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'Identity'

### ISSUE THREAD

**Issue by hongweizeng** [asyml/texar-pytorch#123]
The error occurs when I am running the example of gpt-2.

python gpt2_generate_main.py --is_interactive \
--max_decoding_length=100 \
--temperature=0.7 \
--top_k=40

![image](https://user-images.githubusercontent.com/15373554/61923119-63270400-af95-11e9-9e98-78618a69fb89.png)

torch version: 1.0.0

**Comment by gpengzhi** [comment]
@hongweizeng Thank you for submitting the issue. This should be a version-related issue. There is no `nn.Identity` in `torch 1.0.0`. I will fix this soon.

**Comment by kysunami** [comment]
Were you able to fix this? I am facing the same issue while integrating old version code with efficientnet_pytorch viz available in newer version.. else only fix left is to add my own files for efficientnet and modify the various function calls thatt are incompatible
