### ISSUE TITLE
ModuleNotFoundError: No module named 'texar.torch'import

### ISSUE THREAD

**Issue by GenTxt** [asyml/texar-pytorch#130]
Installed texar (tf version) fine but having problems running scripts in texar-pytorch.

All scripts return this error:

ModuleNotFoundError: No module named 'texar.torch'import

For example: xlnet_generation_main.py 

Have installed according to instructions. Can import "texar" followed by "torch" from python but not "import texar.torch as tx" at the start of each script.

Should a path be added? Any help appreciated.

pip install -e .

Installing collected packages: numpy, idna, certifi, chardet, urllib3, requests, funcsigs, mypy-extensions, texar-pytorch
  Found existing installation: texar-pytorch 0.0.1
    Uninstalling texar-pytorch-0.0.1:
      Successfully uninstalled texar-pytorch-0.0.1
  Running setup.py develop for texar-pytorch

python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import texar.torch as tx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'texar.torch'import 
>>> import texar
>>> import torch
>>>

**Comment by huzecong** [comment]
Can you confirm that you've installed Texar-PyTorch from the latest commit (507932c)? Can you check if you can access modules directly under `texar`, e.g., `texar.HParams`? If you could, you may be using an out-of-date version.

**Comment by GenTxt** [comment]
Removed old. Downloaded and installed latest: texar-pytorch-507932c899ca3a8663479b31efc3a41bc7180693.zip

Same error.

**Comment by huzecong** [comment]
Sorry but I cannot reproduce the error. Can you try again in a fresh virtualenv, and post the full output here? Also, can you share your system information (Linux distro & version)?

**Comment by GenTxt** [comment]
ubuntu 18.04, 1070 gpu, python 3.6.8, tf 1.14

Set up virtual environment. 

Installed /home/pixelhead/p3_environment_directory/sample_environment/texar-pytorch.

Activated. Different error. No module named 'torch'

(sample_environment) pixelhead@pixelhead-AA-1956:~/p3_environment_directory/sample_environment/texar-pytorch/examples/xlnet$ 
python3 xlnet_generation_main.py
Traceback (most recent call last):
  File "xlnet_generation_main.py", line 19, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

------------------------
(sample_environment) pixelhead@pixelhead-AA-1956:~/p3_environment_directory/sample_environment/texar-pytorch/examples/xlnet$ 
python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
>>> exit()

Tried running "pip3 install texar-pytorch" 

Not a valid install command but returned "Requirement already satisfied:" (???)

(sample_environment) pixelhead@pixelhead--AA-1956:~/p3_environment_directory/sample_environment/texar-pytorch/examples/xlnet$ 
pip3 install texar-pytorch
Requirement already satisfied: texar-pytorch in /home/pixelhead/p3_environment_directory/sample_environment/texar-pytorch
etc.
deactivate

Will remove and wait for another revision. No one else is posting same problem so it must be an issue with my install.

**Comment by huzecong** [comment]
Have you installed PyTorch by running `pip install torch`?

We don't list `torch` as a requirement because people might need different versions of PyTorch (e.g. with CUDA 10) or use different package managers (e.g. `conda`). As a result, it will not be automatically installed.

**Comment by GenTxt** [comment]
Thanks. That appears to have been the problem. :)

Working now
