### ISSUE TITLE
Change seq_len to max_time in the docs.

### ISSUE THREAD

**Issue by AvinashBukkittu** [asyml/texar-pytorch#144]
In other modules' doc we say `[batch_size, max_time]`, instead of `seq_len`. https://github.com/asyml/texar/blob/master/texar/modules/decoders/rnn_decoders.py#L303

Pls keep the terminology consistent. Also, if PyTorch has the same issue, pls fix too

_Originally posted by @ZhitingHu in https://github.com/asyml/texar/pull/182_

**Comment by gpengzhi** [comment]
https://github.com/asyml/texar-pytorch/blob/master/texar/torch/modules/encoders/xlnet_encoder.py#L326
