### ISSUE TITLE
Potential position embedding issue in decoders.

### ISSUE THREAD

**Issue by TomNong** [asyml/texar-pytorch#158]
Currently there is a potential issue in some decoders(e.g. `AttentionRNNDecoder`) which support position embedder. 

In eval mode, given `max_decoding_length`, the `dynamic_decode` will stop at `time==max_decoding_length - 1`, while decoder helper may pass `time = time + 1` to its position embedder. Since `position_size` of the position embedder  is usually equal to `max_decoding_length`, inputing `time==max_decoding_length` will cause `index out of range` error on position embedder.

Suggested by @huzecong , _we could fix this for all decoders by adding a check in the embedding function._

**Comment by huzecong** [comment]
A better way to deal with this might be: split `decoder.step` into two methods, one for computing `next_state` and `output`, another for computing the next input. This way we can perform a check in `dynamic_decode`, without requiring all decoder classes to check for themselves.

**Comment by ZhitingHu** [comment]
Does `TransformerDecoder` have such issue?

Does Texar-TF have such issue? @TomNong can you double-check?

Performing the check in `dynamic_decode` is good. We can refactor the decoder a bit (though I don't know the full details of your suggestion)

**Comment by TomNong** [comment]
@ZhitingHu For `TransformerDecoder` it does not have such issue.

For texar-TF, this issue is related with https://github.com/asyml/texar/issues/199, actually we used `reach_max_time` to avoid this issue.

The check in `dynamic_decode` seems to solve this issue, but it needs `dynamic_decode` to stop when `time + 1 == max_decoding_length`, that will cause error in beam search.
