### ISSUE TITLE
Does texar provide RNN for LM？

### ISSUE THREAD

**Issue by buptcjj** [asyml/texar-pytorch#179]
I want to predict the next word just like GPT2.  
But I want to try RNN first for baseline or efficiency? 
So does texar provide RNN model to do this task, just same as LM?

**Comment by huzecong** [comment]
We provide RNN components (e.g., the [`BasicRNNDecoder`](https://texar-pytorch.readthedocs.io/en/latest/code/modules.html#texar.torch.modules.BasicRNNDecoder)), but you would have to build the model yourself. I would suggest taking a look at the example in the documentation, which basically builds a language model.

**Comment by huzecong** [comment]
Closing this issue due to lack of activities.
