### ISSUE TITLE
Question related to LSTMCell output; (h,c) vs (c, h)

### ISSUE THREAD

**Issue by varinf** [asyml/texar-pytorch#198]
Hi, 

Pytorch's LSTMCell final state output is (h, c), but in texar, (c,h) is used consistently for LSTMStateTuple. Is it a bug? If not, could you please point me to the code when we switch from (h,c) to (c, h)? 

Thanks,
Varun

**Comment by gpengzhi** [comment]
Thank you for the interest in `texar-pytorch`. You can take a look at [LSTMCell](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/core/cell_wrappers.py#L185) in `texar-pytorch`, which is a wrapper over `torch.nn.LSTMCell`.

**Comment by varinf** [comment]
Thanks @gpengzhi for quick reply. My understanding is that LSTMCell is just a wrapper on top of nn.LSTMCell, so it should preserve the (h,c) order. Additionally, in[ LSTMCell initializer,](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/core/cell_wrappers.py#L203) it's mentioned (h,c) so why do we use (c,h) ?

**Comment by gpengzhi** [comment]
Could you point out the place where we use `(c, h)`? The [forward()](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/core/cell_wrappers.py#L215) of LSTMCell returns `new_state[0], new_state` which is actually `h, (h, c)`. Here `(h, c)` is the state of `LSTMCell`, so the return of `zero_state` of `LSTMCell` is correct.

**Comment by varinf** [comment]
The implementation is correctly using (h,c). However in documentation (c, h) is used at multiple places. For example, in connectors module, I found multiple instances mentioning (c, h). [One such instance](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/modules/connectors/connectors.py#L280)

I think this should be updated to avoid confusion. 
Thanks

**Comment by gpengzhi** [comment]
I see. Thanks for letting us know such issue. We will update the `docs` accordingly.
