### ISSUE TITLE
Question about the usage of helper in TransformerDecoder

### ISSUE THREAD

**Issue by ha-lins** [asyml/texar-pytorch#228]
Hi~ 
I want to implement the step-by-step TransformerDecoder with a TrainingHelper(), but I don't know how to call the same forward function as the RNN's, e.g.

`outputs, hidden = self.gru(embedded, hidden)`  # forward for every step

Has it been done in the step method of the class helper ? Hope for your help!

**Comment by gpengzhi** [comment]
Thank you for your interest in Texar-PyTorch!

The forward function for every step ([Here](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/modules/decoders/transformer_decoders.py#L740)) is implemented in `TransformerDecoder`.

You can take a look at [self._inputs_to_outputs](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/modules/decoders/transformer_decoders.py#L299).

**Comment by ha-lins** [comment]
In fact, I have no idea of how the initialize/step function is called or works.  And the step function requires the helper argument. What should I do to build such class of helper? Is there any corresponding example for this?

Thanks!

**Comment by huzecong** [comment]
Sorry but I'm a bit confused. Is your goal to write (from scratch) a new `Helper` class, or to use an alternative built-in helper with the decoder?

**Comment by ha-lins** [comment]
Specifically, I want to modify an alternative helper (e.g. TrainingHelper) instead of writing (from scratch). So I may need a corresponding example to help me to understand and then modify. One of the modification may be to set a teacher_forcing_ratio when feeding the next_inputs.

**Comment by ha-lins** [comment]
@huzecong  Specifically, I want to modify an alternative helper (e.g. TrainingHelper) instead of writing (from scratch). So I may need a corresponding example to help me to understand and then modify. One of the modification may be to set a teacher_forcing_ratio when feeding the next_inputs.

**Comment by huzecong** [comment]
You don't need to do that yourself. `helper.initialize` is called inside `decoder.initialize`, where the decoder will pass its own `embedding_fn` to the helper.

The flow of execution would be:

1. Construct a helper.
2. Call `decoder.forward` with the constructed helper.
3. `decoder.forward` calls `DecoderBase.dynamic_decode`.
4. `DecoderBase.dynamic_decode` calls `decoder.initialize`, which in turns calls `helper.initialize`.
5. `DecoderBase.dynamic_decode` loops over each time step and calls `decoder.step`, which in turn calls `helper.sample`.
6. If the current step is not the final time step, `DecoderBase.dynamic_decode` calls `decoder.next_inputs`, which calls `helper.next_inputs`.
7. `DecoderBase.dynamic_decode` calls `decoder.finalize`.

This may not apply to every decoder--helper pair but is a general description of how things work.

**Comment by ha-lins** [comment]
Thanks for your detailed instruction!
