### ISSUE TITLE
Mistake in documentation?

### ISSUE THREAD

**Issue by huhk-sysu** [asyml/texar-pytorch#243]
I'm using texar-pytorch v0.1.0.

In the example [here](https://texar-pytorch.readthedocs.io/en/latest/code/run.html#texar.torch.run.Executor.on_event):
```python
@executor.on_event(Event.Epoch, 'end')
def log_at_end_of_epoch(executor):
    logging.info("Epoch %d done", executor.status.epoch)
```
`executor.status.epoch` should be `executor.status['epoch']` since `executor.status` is a `dict` and `epoch` is a key rather than an attribute.

Here's the error I met in experiment.
![image](https://user-images.githubusercontent.com/14769033/68675216-653bbf80-0592-11ea-8018-aa0bd16cc2b8.png)

**Comment by huzecong** [comment]
Yes, you're right. Sorry about this mistake. Would you like to create a pull request for this?
