### ISSUE TITLE
Bugs in data_iterators.py

### ISSUE THREAD

**Issue by li3cmz** [asyml/texar-pytorch#247]
https://github.com/asyml/texar-pytorch/blob/267bfd7f5fbb6c27e1a35c85aedab6edb124903b/texar/torch/data/data/data_iterators.py#L426

The code above should be:
···
not self._dataset.hparams.allow_smaller_final_batch):
···
from dataset to _dataset

**Comment by gpengzhi** [comment]
It's probably a compatibility issue with PyTorch 1.3.

**Comment by huzecong** [comment]
That's probably the case. @li3cmz could you please share the PyTorch version that you had problems with?

**Comment by li3cmz** [comment]
Got it! My pytorch version is '1.3.0'.

**Comment by ZhitingHu** [comment]
We will add support to 1.3 very soon

**Comment by li3cmz** [comment]
Ok. Thanks!
