### ISSUE TITLE
Is this a bug in VAE?

### ISSUE THREAD

**Issue by yongtaoge** [asyml/texar-pytorch#251]
https://github.com/asyml/texar-pytorch/blob/53d8eade02ae8d578fad1250dd95130ddc20a3b8/examples/vae_text/vae_train.py#L90-L91

**Comment by huzecong** [comment]
Yes, this is indeed wrong. This should be `self.decoder_w_embedder.dim + config_model.latent_dims`, and the unlucky coincidence here is that `batch_size` is equal to `latent_dims` in all our configs. Would you like to create a pull request for this?

**Comment by gpengzhi** [comment]
Thanks for letting us know this bug! @yongtaoge @huzecong is right. It should be `... + config_model.latent_dims` instead of `... + config_model.batch_size`. I will fix it very soon.
