### ISSUE TITLE
Cannot download dataset in bert example

### ISSUE THREAD

**Issue by gpengzhi** [asyml/texar-pytorch#264]
When I run

```
python data/download_glue_data.py --tasks=MRPC
```

I got

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
Processing MRPC...
Traceback (most recent call last):
  File "data/download_glue_data.py", line 152, in <module>
    sys.exit(main(sys.argv[1:]))
  File "data/download_glue_data.py", line 142, in main
    format_mrpc(args.data_dir, args.path_to_mrpc)
  File "data/download_glue_data.py", line 55, in format_mrpc
    f"Train data not found at {mrpc_train_file}"
AssertionError: Train data not found at data/MRPC/msr_paraphrase_train.txt
```

Since you are testing `bert` example, can you investigate this issue? @atif93

**Comment by gpengzhi** [comment]
I believe `texar-tf` also has the same issue.

**Comment by atif93** [comment]
@gpengzhi Are you running this on MacOS or Linux?

**Comment by gpengzhi** [comment]
MacOS. Run on my laptop.

**Comment by atif93** [comment]
Okay, I'm not able to reproduce this on my Mac or the linux machine. 
I suspect it's because of some problem in openssl or wget installed on your machine.
Can you reinstall wget and check if it works?

**Comment by atif93** [comment]
```
brew uninstall wget
brew install wget

**Comment by ynebula** [comment]
You can download all files except '--task' option
and you will be downloading all files including MRPC

and you can download it in another way

please read comments in download_glue_data.py 
''' Script for downloading all GLUE data.

Note: for legal reasons, we are unable to host MRPC.
You can either use the version hosted by the SentEval team, which is already tokenized, 
or you can download the original data from (https://download.microsoft.com/download/D/4/6/D46FF87A-F6B9-4252-AA8B-3604ED519838/MSRParaphraseCorpus.msi) and extract the data from it manually.
For Windows users, you can run the .msi file. For Mac and Linux users, consider an external library such as 'cabextract' (see below for an example).
You should then rename and place specific files in a folder (see below for an example).

mkdir MRPC
cabextract MSRParaphraseCorpus.msi -d MRPC
cat MRPC/_2DEC3DBE877E4DB192D17C0256E90F1D | tr -d $'\r' > MRPC/msr_paraphrase_train.txt
cat MRPC/_D7B391F9EAFF4B1B8BCE8F21B20B1B61 | tr -d $'\r' > MRPC/msr_paraphrase_test.txt
rm MRPC/_*
rm MSRParaphraseCorpus.msi

1/30/19: It looks like SentEval is no longer hosting their extracted and tokenized MRPC data, so you'll need to download the data from the original source for now.
2/11/19: It looks like SentEval actually *is* hosting the extracted data. Hooray!
'''

**Comment by atif93** [comment]
Yes, you can download all the files if you don't use the `--tasks` option.  
This issue is not related to that though.
