### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by huzecong** [asyml/texar-pytorch#27]
Currently there are a plethora of issues with the documentation. In a certain sense, documentation is more important than code for end-users so we should also fix these before release.

- [x] Add CI test for building documentations.
- [x] Fix docstrings with incorrect/inconsistent Sphinx format. Examples include:
	- Unescaped markup characters: `"*_keep_prob"` should be `"\*_keep_prob"`. Also make sure **all docstrings are raw strings** (`r"""docstring"""`).
	- Incorrect indentation: Docstrings should follow same indentation as code (4 spaces).
	- Collapsed strings where there should be structures (e.g. lists).
		```
		Wrong (will render as one line):
		- This is a long line that
        is wrapped.
        - Second item.
		Correct:
		- This is a long line that
		  is wrapped.
        - Second item.
		```
	- Modules, classes, method, attributes should use corresponding Sphinx roles (`:mod:`, `:class:`, `:meth:`, `:attr:`).
	- String literals, code snippets, and other identifiers that should be in monospace font should be in monospace font (``` ``"string"`` ```, `` :python:`code` ``, ``` ``identifier`` ```).
- [x] Fix docstrings that are incorrect. Examples include:
	- Method docstrings with arguments that no longer exist.
	- Class docstrings with attributes / `__init__` arguments that no longer exist.
	- Code examples that still use TensorFlow functions, or do not conform to the current APIs should be changed accordingly.
	- External links to PyTorch documents should exist for each PyTorch class/function/module referenced.

This is tedious work for the document maintainer, so in the future, I hope each contributor could also make sure that the docstrings you added conform to the above standards when you make a pull requests.

**Comment by ZhitingHu** [comment]
Inconsistency of `AttentionRNNDecoder` docs to be fixed, e.g., [here](https://github.com/asyml/texar-pytorch/blob/master/texar/modules/decoders/rnn_decoders.py#L274-L297)  @gpengzhi

**Comment by ZhitingHu** [comment]
Delete the warning box [here](https://texar-pytorch.readthedocs.io/en/latest/code/modules.html#texar.modules.TransformerDecoder.forward) if `beam-search` is indeed supported

**Comment by ZhitingHu** [comment]
`"output_dim"` occurs twice: https://github.com/asyml/texar-pytorch/blob/master/texar/modules/decoders/transformer_decoders.py#L181
