### ISSUE TITLE
Switch between model.train() and model.eval()

### ISSUE THREAD

**Issue by li3cmz** [asyml/texar-pytorch#310]
https://github.com/asyml/texar-pytorch/blob/95f3d644680656f38b7b1779f2ba184ef9e1f81a/examples/bert/bert_classifier_main.py#L164

Hello, 
     I find that after doing "_eval_epoch()"，you don't switch model.eval() to model.train(). Wouldn't that be a problem?

**Comment by huzecong** [comment]
Hmm, this is a very good point, thank you for your report. @gpengzhi @AvinashBukkittu Could you verify this and maybe rerun the experiments?
