### ISSUE TITLE
Does BahdanauMonotonicAttention output attention alignments in range [0,1]?

### ISSUE THREAD

**Issue by hadaev8** [asyml/texar-pytorch#325]
From code seems like no.

**Comment by gpengzhi** [comment]
Hi, I think you could take a look at [_monotonic_probability_fn](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/core/attention_mechanism.py#L597) and [monotonic_attention](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/core/attention_mechanism.py#L498)
