### ISSUE TITLE
texar-pytorch:   RuntimeError: expected scalar type Long but found Float

### ISSUE THREAD

**Issue by mufeiteng** [asyml/texar-pytorch#327]
![Screenshot from 2020-10-28 19-04-34](https://user-images.githubusercontent.com/13427950/97428084-740cb500-1950-11eb-8c36-891b2e0a99c6.png)

A error occurs when I run beam search decoder. And I think the error code should be **line 490** in the picture.
I think the correct code for this operation is:    topk_beam_index = topk_ids **//** vocab_size

**Comment by gpengzhi** [comment]
Sorry for the late reply. We will take a look at it asap. Thank a lot for your interest in `texar-pytorch`!

**Comment by TomNong** [comment]
@mufeiteng sorry, this one was created by typo I think
