### ISSUE TITLE
Wordpiece tokenizer tokenize_with_span(text) should return the span begin and end relative to the text 

### ISSUE THREAD

**Issue by jennyzhang-petuum** [asyml/texar-pytorch#343]
Wordpiece tokenizer `tokenize_with_span(text)` method should return the span begin and end relative to the text rather than the token. Since `whitespace_tokenize` is called on input `text` within the function to get the tokens, we should return span begin and end relative to the text directly to avoid another round of tokenization.

**Comment by gpengzhi** [comment]
Resolved
