### ISSUE TITLE
Issue in DataIterator.__len__

### ISSUE THREAD

**Issue by mylibrar** [asyml/texar-pytorch#350]
The current implementation of [`DataIterator.__len__`](https://github.com/asyml/texar-pytorch/blob/5d67ae957763a3683ce8dd5e4d1208cc9fdb4d33/texar/torch/data/data/data_iterators.py#L551) is
```python
def __len__(self):
        return len(self._datasets[self._validate_dataset_name(None)])
```
This only works for `DataIterator` that only contains a single dataset. Otherwise it will trigger a [ValueError](https://github.com/asyml/texar-pytorch/blob/5d67ae957763a3683ce8dd5e4d1208cc9fdb4d33/texar/torch/data/data/data_iterators.py#L511).
For example, if I run the following code snippet:
```python
dataiterator = DataIterator(datasets={'ds1': dataset1, 'ds2': dataset2})
dataiterator.switch_to_dataset('ds2')
print(len(dataiterator))
```
The expected behavior would be to print out the length of `dataset2`, but instead it raised a [ValueError](https://github.com/asyml/texar-pytorch/blob/5d67ae957763a3683ce8dd5e4d1208cc9fdb4d33/texar/torch/data/data/data_iterators.py#L511).
Maybe we should update the implementation of `DataIterator.__len__` to something like:
```python
def __len__(self):
        return len(self._datasets[self._validate_dataset_name(self._current_dataset_name)])
```
in order to avoid this problem.

**Comment by huzecong** [comment]
Good find! I believe there was a previous PR (#334) that tried to address this same issue, but it was not merged and there were no updates from the PR author since. It'd be great if you open a PR with your proposed fix.
