### ISSUE TITLE
Will texar-pytorch support "Text Style Transfer" ?

### ISSUE THREAD

**Issue by XinDongol** [asyml/texar-pytorch#39]
Texar(-TensorFlow) supports [Text Style Transfer](https://github.com/asyml/texar/tree/master/examples/text_style_transfer), which is very nice. 

Will texar-pytorch support "Text Style Transfer" ? 
Thanks!

**Comment by huzecong** [comment]
Hi @XinDongol, thank you for your interest in texar-PyTorch! We have plans to migrate all examples from the TensorFlow, and text style transfer is definitely on the todo-list! These examples should be available in the near future.

**Comment by XinDongol** [comment]
That's great! Thanks for your work~
