### ISSUE TITLE
Add "output_size" for all Texar modules

### ISSUE THREAD

**Issue by huzecong** [asyml/texar-pytorch#42]
In PyTorch, users are required to know the output size of previous modules in order to create parameters for following modules that take as input the previous outputs. For certain modules, manually computing the output size could be difficult for the user (e.g. convolutional layers). It would be useful to add an `output_size` property to `ModuleBase`.

**Comment by gpengzhi** [comment]
Is this issue resolved? If so, maybe we can close it? @huzecong @TomNong

**Comment by huzecong** [comment]
Yes, solved in #101.
