### ISSUE TITLE
embedder_utils.get_embedding: No need to update the reference of embedding with the return value from initializers

### ISSUE THREAD

**Issue by haoransh** [asyml/texar-pytorch#47]
In the current implementation of [embedder_utils.get_embedding](https://github.com/asyml/texar-pytorch/blob/master/texar/modules/embedders/embedder_utils.py#L151), it update the reference of `embedding` with the return value of initialization function. However, this is not necessary because the initialization functions in Pytorch are in-place operations. Moreover it will cause error with the customized initialization such as https://github.com/asyml/texar-pytorch/blob/master/texar/custom/initializers.py#L10.

**Comment by huzecong** [comment]
Fixed by #48.
