### ISSUE TITLE
AttentionRNNDecoder interface refactor

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar-pytorch#55]
Requiring `input_size` and `encoder_output_size`, especially in `AttentionRNNDecoder`, is too much, e.g., [here](https://github.com/asyml/texar-pytorch/blob/master/examples/seq2seq_attn/seq2seq_attn.py#L66-L69):
```
tx.modules.AttentionRNNDecoder(
            encoder_output_size=(self.encoder.cell_fw.hidden_size +
                                 self.encoder.cell_bw.hidden_size),
            input_size=self.target_embedder.dim + config_model.decoder
            ['attention']['attention_layer_size'],
            ...)
```

Can we refactor the interface a bit so that sth like
```
encoder_output_size=self.encoder.output_size,
input_size=self.target_embedder.dim
```
is enough?

related issue: https://github.com/asyml/texar-pytorch/issues/42

@gpengzhi @huzecong @TomNong

**Comment by huzecong** [comment]
I am in favor of this change. For `input_size`, we can make this the size without the concat'd attention vector, as you demonstrated. For `encoder_output_size`, we'd have to wait until #42 is solved.
