### ISSUE TITLE
Path in Transformer Example is wrong

### ISSUE THREAD

**Issue by bigabig** [asyml/texar-pytorch#61]
Hello,

just wanted to report a small mistake in the wmt_14_en_de.sh script (Transformer Example):

lines 22+23:
```
DOWNLOADED_DATA_DIR="data/en_de_temp/"
OUTPUT_DIR_CACHE="${DOWNLOADED_DATA_DIR}/cache"
```
OUTPUT_DIR_CACHE is then data/en_de_temp//cache. The double slash is at least on my system a problem.

You can easily fix this by removing one slash.

**Comment by huzecong** [comment]
Could you share your system environment? I'm guessing you're using some kind of Linux subsystem under Windows (either Cygwin or WSL), because double slashes should be interpreted without problem under Linux-based systems.

**Comment by ZhitingHu** [comment]
Can we use `os.path.join` to make it platform independent?

**Comment by haoransh** [comment]
@ZhitingHu I'm afraid not. It's a shell script. We'd better modify as the suggestion of @bigabig .

**Comment by huzecong** [comment]
The issue is in a Bash script, which is supposed to be run on Linux systems only. I'm not sure if Windows-based Linux subsystems behave differently when double slashes are encountered. For now, I think it's safe to remove that final dash from `DOWNLOADED_DATA_DIR`.

**Comment by ZhitingHu** [comment]
Just realized is in the Bash script. Then it's quick to fix:)

**Comment by bigabig** [comment]
yes i am using windows and executed the script with git bash. Removing the final dash from `DOWNLOADED_DATA_DIR` was fine for me.
