### ISSUE TITLE
seq2seq_attn example polish

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar-pytorch#63]
- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L23 ---> `from texar.core import ...` : do not expose too many library internal details 

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L85 ---> `helper_train = self.decoder.create_helper(decoding_strategy="train_greedy")`: add readibility

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L107
Is it necessary to convert to `tensor`. Can this be done internally?

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L111
Concat right after `enc_outputs` is obtained

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L113 
This should be in config file

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L128
`parameters()` vs `trainable_variables()` ?

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L132-L133
it's weird to get `iterator` from `data_iterator`

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L137
Is it common?

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L155
Mode in `{train, eval, predict}` or `{train, val}`

- [x] Add beam-search

**Comment by huzecong** [comment]
> * [ ]  https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L107
>   
>   Is it necessary to convert to `tensor`. Can this be done internally?

This could just be a Python `int`.

> * [ ]  https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L128
>   
>   `parameters()` vs `trainable_variables()` ?

Personally, I think it's unnecessary to have the `trainable_variables()` method at all. It's almost identical to `parameters()`, and using `parameters()` is the norm. Actually, non-trainable variables should be made "buffers" in PyTorch, that way they don't show up in `parameters()`.

> * [ ]  https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L132-L133
>   
>   it's weird to get `iterator` from `data_iterator`

The `data_iterator` can be iterated over directly, i.e., it is valid to write:
```python
data_iterator.switch_to_train_data()
for batch in data_iterator: ...
```
or:
```python
for batch in data_iterator.get_train_iterator(): ...
```

> * [ ]  https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/seq2seq_attn/seq2seq_attn.py#L137
>   
>   Is it common?

No. This is only used during debugging, when you suspect certain values became NaN.
