### ISSUE TITLE
gpt2 example polish

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar-pytorch#67]
- [x] Port [gpt2_train_main.py](https://github.com/asyml/texar/blob/master/examples/gpt-2/gpt2_train_main.py) too

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/gpt-2/gpt2_generate_main.py#L26-L28
do not expose internal details. ---> `from texar.modules import TransformerDecoder`

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/gpt-2/gpt2_generate_main.py#L84-L95
Too sparse. Reformat to sth like 
```
parser.add_argument(
    '--config_model',
    ...
```

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/gpt-2/gpt2_generate_main.py#L100
Should this inherit `nn.Module` or `texar.ModuleBase`?

- [x] https://github.com/asyml/texar-pytorch/blob/dc51de295da9e861d739bf40ee4902cf8669ca53/examples/gpt-2/gpt2_generate_main.py#L197-L198
Better to print a message

**Comment by huzecong** [comment]
Reopening this issue because [gpt2_train_main.py](https://github.com/asyml/texar/blob/master/examples/gpt-2/gpt2_train_main.py) is not yet ported.

**Comment by huzecong** [comment]
I don't think this issue has been fully addressed, at least not in the master branch.

**Comment by gpengzhi** [comment]
I am working on `gpt` modules and can take care of the remaining work.
