### ISSUE TITLE
Make bleu_tool.py the same as in TF

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar-pytorch#88]
Make sure `examples/transformer/bleu_tool.py` is the same as the Texar-TF version

related issue: https://github.com/asyml/texar/issues/174

**Comment by gpengzhi** [comment]
Is there any specific reason that we create a new `bleu_tool.py` in `transformer` example? Can we directly use the functions in `texar.eval`? If not, is it possible for us to enrich the current `texar.eval`?

**Comment by ZhitingHu** [comment]
There are several versions of BLEU implementation, including `texar.evals.bleu_moses` (the most), `texar.evals.bleu`, and `bleu_tool` (which looks specifically used in transformer).. 

It'd be nice to integrate `bleu_tool` in `texar.evals`, but this can be of lower priority
