### ISSUE TITLE
Not support Windows system？

### ISSUE THREAD

**Issue by Codle** [asyml/texar-pytorch#94]
When I run the code in Windows, I met the error

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead

and I run the same codes in Linux, all things were OK.

I had checked the pytorch version were both 1.1.0.

**Comment by Codle** [comment]
the codes I used were seq2seq_attn example, and the error was occured in embeding layer.

**Comment by huzecong** [comment]
Thank you for the feedback! I'm guessing the error is not related to Windows, it's probably due to some mistakes in tensor device placement. Could you share the complete error message along with the stacktrace? This will help us locate the bug.

**Comment by Codle** [comment]
> Thank you for the feedback! I'm guessing the error is not related to Windows, it's probably due to some mistakes in tensor device placement.
> 
> Could you share the hash of the commit you're working on, and the complete error message along with the stacktrace? This will help us locate the bug.

I remove my cuda code. Now the file was copied form example/seq2seq_attn/seq2seq_attn.py and the error was

```
Traceback (most recent call last):
  File "seq2seq_attn.py", line 186, in <module>
    main()
  File "seq2seq_attn.py", line 172, in main
    _train_epoch()
  File "seq2seq_attn.py", line 138, in _train_epoch
    loss = model(batch, mode="train")
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq_attn.py", line 81, in forward
    inputs=self.source_embedder(batch['source_text_ids']),
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\projects\texar-pytorch\texar\modules\embedders\embedders.py", line 221, in forward
    outputs = F.embedding(ids, embedding, **kwargs)
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)
```

**Comment by gpengzhi** [comment]
Thank you for the feedback! `RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)` My guess is that the type of `batch['source_text_ids']` is wrong. `batch['source_text_ids']` here should be a `LongTensor`. We recently did some code refactor on `data` module and `seq2seq_attn` example. Could you try the lastest `seq2seq_attn` example to see if such error still exists?

**Comment by Codle** [comment]
> Thank you for the feedback! `RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)` My guess is that the type of `batch['source_text_ids']` is wrong. `batch['source_text_ids']` here should be `LongTensor`. We recently did some code refactor on `data` module and `seq2seq_attn` example. Could you try the lastest `seq2seq_attn` example to see if such error still exists?

It's useless. But I checked the `batch['source_text_ids']`, the dtype is `dtype=torch.int32`. So I think this is the problem.

And I run the example successfully by add `.long()` in line 76, 89, 93

```
76:inputs=self.source_embedder(batch['source_text_ids'].long()),
89:inputs=self.target_embedder(batch['target_text_ids'][:, :-1].long()),
93:labels=batch['target_text_ids'][:, 1:].long(),
```

**Comment by huzecong** [comment]
@Codle Could you confirm that you're using the latest version of Texar-PyTorch? I could not reproduce the problem in the latest version.

**Comment by Codle** [comment]
> @Codle Could you confirm that you're using the latest version (commit [5e899bf](https://github.com/asyml/texar-pytorch/commit/5e899bf359829dec1e08de90bb337d0dd239d3fc)) of Texar-PyTorch? I could not reproduce the problem in the latest version.

```
(base) C:\Users\codle\Documents>pip uninstall texar
Uninstalling texar-0.0.1:
  Would remove:
    c:\users\codle\anaconda3\lib\site-packages\texar.egg-link
Proceed (y/n)? y
  Successfully uninstalled texar-0.0.1

(base) C:\Users\codle\Documents>git clone https://github.com/asyml/texar-pytorch.git
Cloning into 'texar-pytorch'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 2899 (delta 1), reused 31 (delta 1), pack-reused 2857
Receiving objects: 100% (2899/2899), 1.08 MiB | 473.00 KiB/s, done.
Resolving deltas: 100% (2162/2162), done.

(base) C:\Users\codle\Documents>cd texar-pytorch

(base) C:\Users\codle\Documents\texar-pytorch>pip install -e .
Obtaining file:///C:/Users/codle/Documents/texar-pytorch
Requirement already satisfied: numpy in c:\users\codle\anaconda3\lib\site-packages (from texar==0.0.1) (1.16.2)
Requirement already satisfied: pyyaml in c:\users\codle\anaconda3\lib\site-packages (from texar==0.0.1) (5.1)
Requirement already satisfied: requests in c:\users\codle\anaconda3\lib\site-packages (from texar==0.0.1) (2.21.0)
Requirement already satisfied: funcsigs in c:\users\codle\anaconda3\lib\site-packages (from texar==0.0.1) (1.0.2)
Requirement already satisfied: mypy_extensions in c:\users\codle\anaconda3\lib\site-packages (from texar==0.0.1) (0.4.1)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\codle\anaconda3\lib\site-packages (from requests->texar==0.0.1) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\codle\anaconda3\lib\site-packages (from requests->texar==0.0.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\codle\anaconda3\lib\site-packages (from requests->texar==0.0.1) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\codle\anaconda3\lib\site-packages (from requests->texar==0.0.1) (2.8)
Installing collected packages: texar
  Running setup.py develop for texar
Successfully installed texar

(base) C:\Users\codle\Documents\texar-pytorch>cd examples\seq2seq_attn
(base) C:\Users\codle\Documents\texar-pytorch\examples\seq2seq_attn>python prepare_data.py --data toy_copy
Successfully downloaded toy_copy.zip.

(base) C:\Users\codle\Documents\texar-pytorch\examples\seq2seq_attn>python seq2seq_attn.py --config_model config_model --config_data config_toy_copy
Traceback (most recent call last):
  File "seq2seq_attn.py", line 184, in <module>
    main()
  File "seq2seq_attn.py", line 170, in main
    _train_epoch()
  File "seq2seq_attn.py", line 137, in _train_epoch
    loss = model(batch, mode="train")
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq_attn.py", line 76, in forward
    inputs=self.source_embedder(batch['source_text_ids']),
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\codle\documents\texar-pytorch\texar\modules\embedders\embedders.py", line 221, in forward
    outputs = F.embedding(ids, embedding, **kwargs)
  File "C:\Users\codle\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead (while checking arguments for embedding)


```

**Comment by Codle** [comment]
I tried a experiment to reproduce the error:

```
In [17]: a = torch.from_numpy(np.array([1, 2, 3]))
In [18]: a
Out[18]: tensor([1, 2, 3], dtype=torch.int32)
In [19]: embed(a)
```
then the error was showed. 

In the file `data/paired_text_data.py` 's line 427 was used the function `from_numpy`. Is this function's problem or my computer's?

**Comment by huzecong** [comment]
@Codle Thank you for the details! I had no idea about `np.long` being platform-dependent.

The root cause of the issue is in the `padded_batch` method in `texar/data/data/dataset_utils.py`, where a NumPy array with dtype `np.long` is created. Changing dtype to the platform-independent `np.int64` should work.

I am sorry for the inconvenience. We have not tested the code on Windows because we do not have Windows working environments. Thank you for your contribution!
